### ISSUE TITLE
No resource identifier ound

### ISSUE THREAD

**Issue by YuganshT79** [Cleveroad/PlayWidget#4]
I am having errors in my main_activity layout file

Error:(18) No resource identifier found for attribute 'pa_progress_line_enabled' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_buttons_size' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_image_src' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_progress_ball_color' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_progress_complete_line_color' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_progress_line_color' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_progress_ball_radius' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_progress_complete_line_stroke_width' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_progress_line_stroke_width' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_progress_line_padding' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_diffusers_padding' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_big_diffuser_shadow_width' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_medium_diffuser_shadow_width' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_small_diffuser_shadow_width' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_big_diffuser_color' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_medium_diffuser_color' in package 'ytapps.playbubble'
Error:(18) No resource identifier found for attribute 'pa_play_button_background_tint' in package 'ytapps.playbubble'

What should i do?

**Comment by ValeryGes** [comment]
Hi @CoderYugansh, thank you for your feedback.
We will check this issue and fix it for next release.

With best regards, Cleveroad team.

**Comment by YuganshT79** [comment]
Ok Cool , waiting for the fix

**Comment by yatsinskiyCR** [comment]
Hi @CoderYugansh , Please have a look at https://github.com/Cleveroad/PlayWidget/issues/6. Sorry for long delay.
