### ISSUE TITLE
NO Resource Identifier found

### ISSUE THREAD

**Issue by kunal52** [Cleveroad/PlayWidget#5]
Error:(8) No resource identifier found for attribute 'pa_progress_line_enabled' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_buttons_size' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_image_src' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_ball_color' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_complete_line_color' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_line_color' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_ball_radius' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_complete_line_stroke_width' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_line_stroke_width' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_line_padding' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_diffusers_padding' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_big_diffuser_shadow_width' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_medium_diffuser_shadow_width' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_small_diffuser_shadow_width' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_big_diffuser_color' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_medium_diffuser_color' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_play_button_background_tint' in package 'com.example.kunal.circulartesting'
Error:(15, 27) No resource found that matches the given name (at 'pa_image_src' with value '@drawable/pa_image').
C:\Users\kunal\Desktop\CircularTesting\app\build\intermediates\res\merged\debug\layout\activity_main.xml
Error:(8) No resource identifier found for attribute 'pa_progress_line_enabled' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_buttons_size' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_image_src' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_ball_color' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_complete_line_color' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_line_color' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_ball_radius' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_complete_line_stroke_width' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_line_stroke_width' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_progress_line_padding' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_diffusers_padding' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_big_diffuser_shadow_width' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_medium_diffuser_shadow_width' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_small_diffuser_shadow_width' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_big_diffuser_color' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_medium_diffuser_color' in package 'com.example.kunal.circulartesting'
Error:(8) No resource identifier found for attribute 'pa_play_button_background_tint' in package 'com.example.kunal.circulartesting'
Error:(15, 27) No resource found that matches the given name (at 'pa_image_src' with value '@drawable/pa_image').
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
Information:BUILD FAILED
Information:Total time: 7.969 secs
Information:37 errors
Information:0 warnings
Information:See complete output in console

**Comment by yatsinskiyCR** [comment]
Hi, @kunal52, Please have a look at https://github.com/Cleveroad/PlayWidget/issues/6
