### ISSUE TITLE
No resource identifier found for attribute

### ISSUE THREAD

**Issue by Samarendra109** [Cleveroad/PlayWidget#6]
C:\NewApp1\app\src\main\res\layout\activity_main.xml
Error:(15) No resource identifier found for attribute 'pa_progress_line_enabled' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_buttons_size' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_image_src' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_ball_color' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_complete_line_color' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_ball_radius' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_line_color' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_complete_line_stroke_width' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_line_stroke_width' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_line_padding' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_diffusers_padding' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_big_diffuser_shadow_width' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_medium_diffuser_shadow_width' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_small_diffuser_shadow_width' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_big_diffuser_color' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_medium_diffuser_color' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_play_button_background_tint' in package 'com.example.newu.newapp1'
Error:(22, 31) No resource found that matches the given name (at 'pa_image_src' with value '@drawable/pa_image').
C:\NewApp1\app\build\intermediates\res\merged\debug\layout\activity_main.xml
Error:(15) No resource identifier found for attribute 'pa_progress_line_enabled' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_buttons_size' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_image_src' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_ball_color' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_complete_line_color' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_line_color' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_ball_radius' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_complete_line_stroke_width' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_line_stroke_width' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_progress_line_padding' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_diffusers_padding' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_big_diffuser_shadow_width' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_medium_diffuser_shadow_width' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_small_diffuser_shadow_width' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_big_diffuser_color' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_medium_diffuser_color' in package 'com.example.newu.newapp1'
Error:(15) No resource identifier found for attribute 'pa_play_button_background_tint' in package 'com.example.newu.newapp1'
Error:(22, 31) No resource found that matches the given name (at 'pa_image_src' with value '@drawable/pa_image').
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

I am getting this error. Tell me if i have done something wrong. You have kept a download option in the page . Do we have to download that first or just dependencies will do. If we have to download then what we have to do with the downloaded file. Please help me out.

**Comment by yatsinskiyCR** [comment]
Hi @Samarendra109, Could you describe, how do you use the library in your project?

**Comment by yatsinskiyCR** [comment]
Hello @Samarendra109 , Please use prefix pw_ instead of pa_ in your xml attributes. Sorry for this mistake.
