### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ahmid9** [Cleveroad/PlayWidget#8]
i want help me
how i can use some sound file in raw folder
show in list and play
thanks

**Comment by ValeryGes** [comment]
Hi, @ahmid9!

Thank you for using our library.
Please specify your question if it is about PlayWidget library. If your interest is just about using resources in raw folder - there is a lot of tutorials in Network. For example - official tutorial you can find here: https://developer.android.com/guide/topics/resources/providing-resources.html

With best regards, Cleveroad team.

**Comment by ahmid9** [comment]
like this not help me
i'm now in begnner

**Comment by ValeryGes** [comment]
Hi, @ahmid9!

We are sorry, but we can't help you with features not related to our library. Use official developer tutorial: https://developer.android.com/guide/index.html. It contains all general information about  android applications developing.

With best regards, Cleveroad team.
